apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: frontend
  replicas: {{ default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: frontend
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
               - key: disktype
                 operator: In
                 values:
                 - node1  
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.dockerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
          - name: NODE_ENV
            value: {{ .Values.node.environment }}