trigger:
  batch: true
  branches:
    include: ['master']
pool:
  vmImage: 'ubuntu-latest'

variables:
  MajorVersion: '1'
  MinorVersion: '0'
  repositoryName: myma/plugin
  helmChartVersion: $(MajorVersion).$(MinorVersion).0
  imageName: $(repositoryName):$(Build.SourceBranchName)
  chartPath: $(Build.SourcesDirectory)/deployment/helm/mymaplugin
  azureSubscription: armbmbk8Connection
  azureContainerRegistryName: bmbdevcontainers

steps:

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: bmbAcr

- task: Docker@2
  displayName: Build and Push Containers
  inputs:
    command: buildAndPush
    repository: $(repositoryName)
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(MajorVersion).$(MinorVersion).$(Build.BuildId)
      $(Build.SourceBranchName)

- task: HelmInstaller@1
  displayName: Helm installer
  inputs:
    helmVersionToInstall: 3.17.1

- task: HelmDeploy@0
  displayName: Helm deploy
  inputs:
    command: package
    chartPath: $(chartPath)
    chartVersion: $(helmChartVersion)
    arguments: '--app-version $(Build.SourceBranchName) --dependency-update'

- task: AzureCLI@1
  displayName: Helm push to acr
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |      
      helm push $(System.ArtifactsDirectory)/mymaplugin-$(helmChartVersion).tgz oci://$(azureContainerRegistryName).azurecr.io/$(repositoryName)

- task: PublishBuildArtifacts@1
  inputs: 
    path: '$(System.ArtifactsDirectory)/mymaplugin-$(helmChartVersion).tgz'
    artifact: MymaPlugin